<script setup>
import {ref,computed,onMounted,onUnmounted} from 'vue';
import {Archive, BookOpen, BriefcaseBusiness, FilePenLine, FolderOpen, Plus, Search, ArrowUpRight, ChevronRight, X, Copy, Sparkles, Check, UserRound, ArrowLeft, Trash2} from 'lucide-vue-next';
const page=ref('experiences'), query=ref(''), tag=ref('전체'), toast=ref(''), modal=ref(null);
const nav=[['profile','내 기본 이력',UserRound],['careers','내 경력',BriefcaseBusiness],['experiences','내 경험',BookOpen],['essays','자소서 보관함',Archive]];
const experiences=ref([
{id:1,title:'의견의 차이를 하나의 방향으로',type:'팀 프로젝트',period:'2025.03 — 2025.06',tags:['협업','소통'],situation:'교내 서비스 개발 프로젝트에서 디자인 완성도와 개발 일정에 대한 의견이 달랐습니다.',action:'팀원들이 중요하게 생각하는 기준을 듣고, 필수 화면과 추가 개선 항목을 함께 구분했습니다.',result:'합의한 필수 기능을 발표 일정에 맞춰 완성했습니다.',lesson:'의견을 설득하기 전에 서로의 우선순위를 이해하는 것이 중요했습니다.',memo:'디자인 담당자의 우려를 구체적으로 듣고 나니 논의가 수월해졌습니다.',career:''},
{id:2,title:'반복되는 업무에서 개선의 실마리를 찾다',type:'인턴',period:'2025.07 — 2025.08',tags:['문제 해결','주도성'],situation:'매주 자료를 정리하는 과정에서 동일한 확인 작업이 반복됐습니다.',action:'반복 항목을 정리하고 공통 확인 양식을 제안했습니다.',result:'팀이 같은 기준으로 자료를 점검할 수 있게 됐습니다.',lesson:'작은 불편을 관찰하는 것이 개선의 출발점입니다.',memo:'동료가 자주 확인하는 항목을 먼저 물어봤습니다.',career:'예시 기업'},
{id:3,title:'처음 맡은 행사, 끝까지 책임지다',type:'동아리',period:'2024.09 — 2024.11',tags:['책임감','기획'],situation:'신규 회원을 위한 교내 행사를 준비했습니다.',action:'업무를 나누고 담당자별 진행 상황을 주기적으로 확인했습니다.',result:'예정된 일정에 행사를 마쳤습니다.',lesson:'진행 상황을 공유하는 과정이 중요했습니다.',memo:'',career:''}
]);
const essays=ref([{id:1,company:'예시 기업',role:'서비스 개발 인턴',season:'2026 하반기',status:'작성 중',questions:[{text:'협업을 통해 문제를 해결한 경험을 알려주세요.',limit:700,answer:'',experienceIds:[]}]},{id:2,company:'샘플 테크',role:'프론트엔드 개발',season:'2026 하반기',status:'작성 완료',questions:[{text:'지원 직무와 관련된 경험을 소개해주세요.',limit:1000,answer:'',experienceIds:[]}]}]);
const careers=ref([{id:1,company:'예시 기업',employment:'인턴',role:'서비스 운영팀',start:'2025-07',end:'2025-08',current:false,duties:'운영 자료 정리 및 팀 업무 지원'}]);
const profile=ref({school:'',major:'',education:'졸업',start:'',end:'',gpa:'',scale:'4.5',certificate:'',issuer:'',certDate:'',certNumber:'',language:'',score:'',testDate:'',expiry:'',military:'미입력',branch:'',rank:'',militaryStart:'',militaryEnd:'',veteran:'미입력',disability:'미입력',details:''});
const active=ref(null), questionIndex=ref(0), recommendation=ref(false), draft=ref({}), detail=ref(null);
const currentQuestion=computed(()=>active.value?.questions[questionIndex.value]);
const tags=['전체','협업','문제 해결','주도성','소통','책임감'];
const filtered=computed(()=>experiences.value.filter(e=>(tag.value==='전체'||e.tags.includes(tag.value))&&(e.title+e.tags.join('')+e.situation).includes(query.value)));
const filteredEssays=computed(()=>essays.value.filter(e=>(e.company+e.role).includes(query.value)));
const matches=computed(()=>{const q=currentQuestion.value?.text||'';return experiences.value.map(e=>({e,score:e.tags.filter(t=>q.includes(t)).length})).sort((a,b)=>b.score-a.score).filter(x=>x.score>0).map(x=>x.e)});
let timer; function notify(msg){toast.value=msg;clearTimeout(timer);timer=setTimeout(()=>toast.value='',3000)}
function go(p){page.value=p;query.value='';recommendation.value=false}
function editExperience(e){draft.value=e?JSON.parse(JSON.stringify(e)):{title:'',type:'프로젝트',period:'',tags:[],situation:'',action:'',result:'',lesson:'',memo:'',career:''};draft.value.tagText=draft.value.tags.join(', ');modal.value='experience'}
function saveExperience(){if(!draft.value.title.trim()){notify('경험 제목을 입력해주세요.');return}const d={...draft.value,tags:draft.value.tagText.split(',').map(x=>x.trim()).filter(Boolean)};delete d.tagText;if(d.id){experiences.value=experiences.value.map(x=>x.id===d.id?d:x)}else experiences.value.push({...d,id:Date.now()});modal.value=null;notify('경험을 저장했습니다. 이번 미리보기 동안 유지됩니다.')}
function editCareer(c){draft.value=c?JSON.parse(JSON.stringify(c)):{company:'',employment:'인턴',role:'',start:'',end:'',current:false,duties:''};modal.value='career'}
function saveCareer(){if(!draft.value.company.trim()){notify('회사명을 입력해주세요.');return}const d={...draft.value};if(d.current)d.end='';if(d.end&&d.start>d.end){notify('종료일을 확인해주세요.');return}if(d.id)careers.value=careers.value.map(x=>x.id===d.id?d:x);else careers.value.push({...d,id:Date.now()});modal.value=null;notify('경력을 저장했습니다.')}
function newEssay(){draft.value={company:'',role:'',season:'2026 하반기'};modal.value='essay'}
function createEssay(){if(!draft.value.company.trim()||!draft.value.role.trim()){notify('회사와 지원 직무를 입력해주세요.');return}const e={...draft.value,id:Date.now(),status:'작성 중',questions:[{text:'',limit:700,answer:'',experienceIds:[]}]};essays.value.unshift(e);modal.value=null;openEssay(e)}
function openEssay(e){active.value=e;questionIndex.value=0;go('editor')}
function recommend(){if(!currentQuestion.value.text.trim()){notify('문항을 먼저 입력해주세요.');return}recommendation.value=true}
function connect(e){const ids=currentQuestion.value.experienceIds;if(!ids.includes(e.id))ids.push(e.id);notify('참고 경험으로 연결했습니다.')}
async function copyProfile(){try{await navigator.clipboard.writeText(Object.entries(profile.value).filter(([,v])=>v).map(([k,v])=>`${labels[k]||k}: ${v}`).join('\n'));notify('기본 이력을 복사했습니다.')}catch{notify('브라우저에서 클립보드 접근을 허용해주세요.')}}
const labels={school:'학교',major:'전공',education:'학적 상태',start:'입학 시기',end:'졸업 시기',gpa:'학점',scale:'만점',certificate:'자격증명',issuer:'발급기관',certDate:'취득일',certNumber:'자격번호',language:'어학 시험명',score:'점수·등급',testDate:'응시일',expiry:'유효기간',military:'병역 구분',branch:'군별',rank:'계급',militaryStart:'복무 시작',militaryEnd:'복무 종료',veteran:'보훈 대상 여부',disability:'장애 여부',details:'추가 정보'};
function removeExperience(){const id=detail.value.id;experiences.value=experiences.value.filter(e=>e.id!==id);essays.value.forEach(e=>e.questions.forEach(q=>q.experienceIds=q.experienceIds.filter(x=>x!==id)));detail.value=null;modal.value=null;notify('경험을 삭제했습니다. 작성한 답변은 유지됩니다.')}
const toolLifecycle=new AbortController();
onMounted(()=>{const context=document.modelContext;if(!context?.registerTool)return;try{Promise.resolve(context.registerTool({name:'navigate_ssulap',description:'Navigate to a ssulap workspace section.',inputSchema:{type:'object',properties:{section:{type:'string',enum:['profile','careers','experiences','essays']}},required:['section'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!nav.some(n=>n[0]===input.section))throw new Error('Invalid section');go(input.section);return {section:page.value}}},{signal:toolLifecycle.signal})).catch(()=>{});}catch{}});
onUnmounted(()=>toolLifecycle.abort());
</script>

<template>
<div class="app-shell">
<aside class="sidebar"><a class="brand" href="#" @click.prevent="go('experiences')"><span class="brand-icon"><Archive :size="23"/></span>써랍<span class="brand-dot">.</span></a><div class="workspace-label">MY WORKSPACE</div><nav><button v-for="[key,label,icon] in nav" :key="key" :class="{selected:page===key||(page==='editor'&&key==='essays')}" @click="go(key)"><component :is="icon" :size="19"/>{{label}}<span v-if="key==='experiences'" class="count">{{experiences.length}}</span></button></nav><div class="side-note"><span class="note-line"></span><p>해온 일을 차곡차곡.<br>쓸 때는 나답게.</p><small>나의 다음 이야기를 위한 서랍</small></div><div class="user"><span class="avatar">나</span><div><b>나의 작업 공간</b><small>개인 전용</small></div></div></aside>
<div class="main-shell"><header class="topbar"><span>나의 써랍 <ChevronRight :size="14"/> {{page==='editor'?'자소서 작성':nav.find(x=>x[0]===page)?.[1]}}</span><span class="demo-badge">프론트엔드 미리보기 · 예시 데이터</span></header>
<main>
<template v-if="page==='experiences'">
<div class="page-heading"><div><div class="eyebrow">MY EXPERIENCES</div><h1>해온 일들이, 나의 이야기가 되도록<span>.</span></h1><p>작은 시도부터 함께 만든 결과까지. 잊기 전에 내 경험을 담아보세요.</p></div><button class="primary" @click="editExperience()"><Plus :size="18"/>경험 기록하기</button></div>
<section class="overview"><div><span class="overline">차곡차곡 모인 경험</span><strong>{{String(experiences.length).padStart(2,'0')}}<small>개의 이야기</small></strong></div><div><span class="overline">경험 속 나의 키워드</span><div class="keywords"><span v-for="t in [...new Set(experiences.flatMap(e=>e.tags))].slice(0,5)">{{t}}</span></div></div><div class="overview-tip"><BookOpen :size="24"/><p>멋진 결과가 아니어도 괜찮아요.<br><b>내가 한 행동에서 이야기는 시작돼요.</b></p></div></section>
<div class="section-heading"><h2>나의 경험 <span>{{experiences.length}}</span></h2><label class="search"><Search :size="17"/><input v-model="query" placeholder="경험이나 키워드 검색" aria-label="경험 검색"></label></div><div class="filters"><button v-for="t in tags" :class="{active:tag===t}" @click="tag=t">{{t}}</button></div>
<div class="experience-grid"><button class="experience-card" v-for="(e,i) in filtered" :key="e.id" @click="detail=e"><div class="card-top"><span class="folder-icon"><FolderOpen :size="24"/></span><span>{{e.type}}</span><ArrowUpRight :size="19"/></div><small>{{e.period}}</small><h3>{{e.title}}</h3><p>{{e.situation}}</p><div class="card-tags"><span v-for="t in e.tags"># {{t}}</span></div><footer>경험 펼쳐보기 <ChevronRight :size="16"/></footer></button><button class="add-card" @click="editExperience()"><span><Plus :size="24"/></span><b>아직 꺼내지 않은 이야기가 있나요?</b><p>새로운 경험을 서랍에 담아보세요.</p></button></div><p v-if="!filtered.length" class="empty">조건에 맞는 경험이 없습니다. 검색어나 태그를 바꿔보세요.</p>
</template>
<template v-if="page==='profile'">
<div class="page-heading"><div><div class="eyebrow">MY PROFILE</div><h1>한 번 정리하고, 필요할 때 꺼내요<span>.</span></h1><p>지원할 때마다 찾던 기본 이력을 한곳에서 관리하세요.</p></div><button class="secondary" @click="copyProfile"><Copy :size="17"/>이력 복사</button></div><form @submit.prevent="notify('입력 내용을 반영했습니다. 새로고침하면 초기화됩니다.')" class="profile-form"><section class="form-section" v-for="(fields,i) in [['school','major','education','start','end','gpa','scale'],['certificate','issuer','certDate','certNumber'],['language','score','testDate','expiry'],['military','branch','rank','militaryStart','militaryEnd'],['veteran','disability','details']]"><h2>{{['학력','자격증','어학 성적','병역사항','보훈·장애사항'][i]}}</h2><p v-if="i===4" class="muted">선택 입력 항목입니다. AI 경험 추천에 사용되지 않습니다.</p><div class="form-grid"><label v-for="f in fields">{{labels[f]}}<select v-if="['military','veteran','disability','education'].includes(f)" v-model="profile[f]"><option v-for="v in (f==='military'?['미입력','해당 없음','미필','복무 중','군필','면제']:f==='education'?['재학','휴학','졸업 예정','졸업']:['미입력','대상','비대상'])">{{v}}</option></select><input v-else v-model="profile[f]" :placeholder="labels[f]+' 입력'"></label></div></section><button class="primary" type="submit"><Check :size="18"/>저장</button></form>
</template>
<template v-if="page==='careers'"><div class="page-heading"><div><div class="eyebrow">MY CAREER</div><h1>일하며 쌓아온 시간<span>.</span></h1><p>인턴부터 첫 직장까지, 나의 경력을 정리해보세요.</p></div><button class="primary" @click="editCareer()"><Plus :size="18"/>경력 추가</button></div><div class="career-card" v-for="c in careers"><span class="folder-icon"><BriefcaseBusiness/></span><div><span class="pill">{{c.employment}}</span><h2>{{c.company}}</h2><p>{{c.role}} · {{c.start}} — {{c.current?'재직 중':c.end}}</p><p>{{c.duties}}</p></div><button class="secondary" @click="editCareer(c)">수정</button></div><p v-if="!careers.length" class="empty">첫 경력을 등록해보세요.</p></template>
<template v-if="page==='essays'"><div class="page-heading"><div><div class="eyebrow">MY APPLICATIONS</div><h1>다음 기회를 준비하는 서랍<span>.</span></h1><p>회사마다 다른 질문에, 나의 경험으로 답해보세요.</p></div><button class="primary" @click="newEssay"><Plus :size="18"/>새 자소서</button></div><label class="search"><Search :size="17"/><input v-model="query" placeholder="회사 또는 지원 직무 검색" aria-label="자소서 검색"></label><div class="essay-list"><button v-for="e in filteredEssays" class="essay-row" @click="openEssay(e)"><span class="folder-icon"><FilePenLine/></span><div><small>{{e.season}}</small><h2>{{e.company}}</h2><p>{{e.role}}</p></div><span class="pill">{{e.status}}</span><ChevronRight/></button><p v-if="!filteredEssays.length" class="empty">자소서가 없습니다. 새 자소서를 만들어보세요.</p></div></template>
<template v-if="page==='editor'&&active"><button class="text-button" @click="go('essays')"><ArrowLeft :size="16"/>보관함으로</button><div class="page-heading editor-heading"><div><div class="eyebrow">{{active.season}} · {{active.role}}</div><h1>{{active.company}}</h1></div><div class="actions"><select v-model="active.status"><option>작성 중</option><option>작성 완료</option><option>제출 완료</option></select><button class="primary" @click="notify('작성 내용을 반영했습니다. 새로고침하면 초기화됩니다.')">저장</button></div></div><div class="editor-layout"><section class="editor-panel"><div class="question-tabs"><button v-for="(q,i) in active.questions" :class="{active:i===questionIndex}" @click="questionIndex=i;recommendation=false">문항 {{i+1}}</button><button @click="active.questions.push({text:'',limit:700,answer:'',experienceIds:[]});questionIndex=active.questions.length-1;recommendation=false"><Plus :size="16"/></button></div><label>자소서 문항<textarea class="question-input" v-model="currentQuestion.text" placeholder="지원할 회사의 문항을 입력해주세요."/></label><label class="limit">글자 수 제한<input type="number" min="1" max="20000" v-model="currentQuestion.limit"></label><label>나의 답변<textarea class="answer-input" v-model="currentQuestion.answer" placeholder="경험을 참고하며 나의 언어로 작성해보세요."/></label><div class="char-count" :class="{error:currentQuestion.answer.length>currentQuestion.limit}">공백 포함 {{currentQuestion.answer.length}} / {{currentQuestion.limit}}자</div><div class="linked">참고한 경험 <span v-for="id in currentQuestion.experienceIds">{{experiences.find(e=>e.id===id)?.title}} <button @click="currentQuestion.experienceIds=currentQuestion.experienceIds.filter(x=>x!==id)" aria-label="경험 연결 해제">×</button></span></div></section><aside class="recommend-panel"><div class="section-heading"><h2>경험 꺼내보기</h2><BookOpen :size="19"/></div><p>문항에 어울리는 내 경험을 찾아보세요.</p><button class="primary full" @click="recommend"><Sparkles :size="17"/>경험 추천받기</button><small class="simulation">시연용 추천 · 문항과 태그를 비교합니다.<br>실제 AI는 연결되지 않았습니다.</small><button v-if="recommendation" class="text-button" @click="recommendation=false">모든 경험 보기</button><p v-if="recommendation&&!matches.length" class="empty">일치하는 키워드가 없습니다. 모든 경험에서 직접 선택해보세요.</p><article class="recommend-card" v-for="e in (recommendation?matches:experiences)"><small>{{e.type}}</small><h3>{{e.title}}</h3><p v-if="recommendation">문항에 포함된 ‘{{e.tags.filter(t=>currentQuestion.text.includes(t)).join(', ')}}’ 키워드와 연결된 경험입니다.</p><div class="card-tags"><span v-for="t in e.tags">#{{t}}</span></div><div class="actions"><button class="text-button" @click="detail=e">상세 보기</button><button class="secondary" @click="connect(e)">{{currentQuestion.experienceIds.includes(e.id)?'연결됨':'참고로 선택'}}</button></div></article><div v-if="recommendation&&matches.length" class="prompt-note"><b>한 번 더 떠올려보세요</b><p>그 상황에서 본인이 직접 한 행동은 무엇인가요? 그 행동으로 무엇이 달라졌나요?</p></div></aside></div></template>
<footer class="page-footer">써랍 · 당신의 다음 이야기를 꺼내는 곳 <span>데이터는 현재 화면에서만 유지되며, 새로고침 시 초기화됩니다.</span></footer>
</main></div>
<div v-if="toast" class="toast" role="status"><Check :size="17"/>{{toast}}</div>
<div v-if="detail" class="overlay" @click.self="detail=null"><section class="dialog detail-dialog" role="dialog" aria-modal="true" aria-label="경험 상세"><button class="close" @click="detail=null" aria-label="닫기"><X/></button><span class="eyebrow">{{detail.type}} · {{detail.period}}</span><h2>{{detail.title}}</h2><div class="card-tags"><span v-for="t in detail.tags">#{{t}}</span></div><div v-for="[k,l] in [['situation','상황·과제'],['action','내 역할·행동'],['result','결과'],['lesson','배운 점'],['memo','협업 회고']]" class="detail-block"><h3>{{l}}</h3><p>{{detail[k]||'아직 기록하지 않았습니다.'}}</p></div><div class="actions"><button class="danger text-button" @click="modal='delete'"><Trash2 :size="16"/>삭제</button><button class="primary" @click="editExperience(detail);detail=null">수정하기</button></div></section></div>
<div v-if="modal" class="overlay modal-layer" @click.self="modal=null"><section class="dialog" role="dialog" aria-modal="true" aria-label="정보 입력"><button class="close" @click="modal=null" aria-label="닫기"><X/></button><template v-if="modal==='delete'"><h2>경험을 삭제할까요?</h2><p>자소서와의 연결도 해제됩니다. 작성한 답변은 유지됩니다.</p><div class="actions"><button class="secondary" @click="modal=null">취소</button><button class="primary" @click="removeExperience">삭제</button></div></template><form v-else @submit.prevent="modal==='experience'?saveExperience():modal==='career'?saveCareer():createEssay()"><div class="eyebrow">YOUR NEXT STORY</div><h2>{{modal==='experience'?'경험 기록하기':modal==='career'?'경력 기록하기':'새 자소서 만들기'}}</h2><template v-if="modal==='experience'"><label>경험 제목 *<input v-model="draft.title" required placeholder="어떤 경험을 하셨나요?"></label><div class="form-grid"><label>활동 유형<input v-model="draft.type" placeholder="프로젝트, 인턴, 동아리 등"></label><label>기간<input v-model="draft.period" placeholder="2025.03 — 2025.06"></label></div><label>관련 경력<select v-model="draft.career"><option value="">연결하지 않음</option><option v-for="c in careers">{{c.company}}</option></select></label><label v-for="[key,name] in [['situation','상황·과제'],['action','내 역할·행동'],['result','결과'],['lesson','배운 점'],['memo','협업 회고 메모 (선택)']]">{{name}}<textarea v-model="draft[key]" :placeholder="key==='memo'?'함께 일한 사람의 역할, 의견 차이, 도움받은 점 등을 기록해보세요.':''"/></label><label>태그<input v-model="draft.tagText" placeholder="협업, 소통 (쉼표로 구분)"></label></template><template v-if="modal==='career'"><label>회사명 *<input v-model="draft.company" required></label><div class="form-grid"><label>근무 형태<select v-model="draft.employment"><option>인턴</option><option>정규직</option><option>계약직</option><option>아르바이트</option><option>기타</option></select></label><label>부서·직무<input v-model="draft.role"></label><label>시작일<input type="month" v-model="draft.start"></label><label>종료일<input type="month" v-model="draft.end" :disabled="draft.current"></label></div><label class="checkbox"><input type="checkbox" v-model="draft.current">재직 중</label><label>담당 업무<textarea v-model="draft.duties"/></label></template><template v-if="modal==='essay'"><label>회사명 *<input v-model="draft.company" required></label><label>지원 직무 *<input v-model="draft.role" required></label><label>지원 시기<input v-model="draft.season"></label></template><div class="dialog-actions"><button type="button" class="secondary" @click="modal=null">취소</button><button class="primary" type="submit">{{modal==='essay'?'작성 시작':'저장'}}</button></div></form></section></div>
</div>
</template>
